# Generated by Django 4.2.6 on 2023-11-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityName', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RulingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magistrate', models.CharField(blank=True, max_length=100)),
                ('obverse_image', models.ImageField(blank=True, null=True, upload_to='coin_images')),
                ('reverse_image', models.ImageField(blank=True, null=True, upload_to='coin_images')),
                ('size', models.FloatField()),
                ('weight', models.FloatField()),
                ('material', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('lead', 'Lead'), ('billon', 'Billon'), ('iron', 'Iron')], max_length=100)),
                ('denomination', models.CharField(blank=True, max_length=100)),
                ('date_range', models.CharField(blank=True, max_length=10)),
                ('date_exact', models.CharField(blank=True, max_length=10)),
                ('obverse', models.TextField(default='')),
                ('reverse', models.TextField(default='')),
                ('reference', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mint_authority', to='CoinCollectionApp.authority')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_category', to='CoinCollectionApp.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins_city', to='CoinCollectionApp.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_region', to='CoinCollectionApp.region'),
        ),
        migrations.AddField(
            model_name='authority',
            name='rulingState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoinCollectionApp.rulingstate'),
        ),
    ]
