# Generated by Django 4.2.6 on 2023-11-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoinCollectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='rulingState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruling_state', to='CoinCollectionApp.rulingstate'),
        ),
    ]
