# Generated by Django 4.2.6 on 2023-11-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinCollectionApp', '0002_alter_authority_rulingstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='endRule',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
