# Generated by Django 4.2.6 on 2023-11-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinCollectionApp', '0004_alter_coin_obverse_image_alter_coin_reverse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='authority_slug',
            field=models.SlugField(default='dlut', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default='glut', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='ciy_slug',
            field=models.SlugField(default='butt', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authority',
            name='endRule',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
