# Generated by Django 4.2.6 on 2023-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinCollectionApp', '0007_authority_startrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
