# Generated by Django 4.2.6 on 2023-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinCollectionApp', '0009_alter_coin_obverse_image_alter_coin_reverse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='end_date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
