# Generated by Django 4.2.6 on 2023-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinCollectionApp', '0010_coin_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='date_range',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
